# configuration, adapt before building

# base installation dir of WIX
WIX_DIR = C:\Program Files\Windows Installer XML v3.5

# where is Qt installed
QT_DIR = C:\Qt\4.8.1

# libraries to link into the installer
WIX_LIBS = dutil_2008.lib wcautil_2008.lib
#WIX_LIBS = dutil_2008_x64.lib wcautil_2008_x64.lib

# architecture of resulting msi
WIX_ARCH = x86
#WIX_ARCH = x64

# define if you want to deploy the debug version
DEBUG = 1

# end configuration

CANDLE = "$(WIX_DIR)\bin\candle.exe"
LIGHT = "$(WIX_DIR)\bin\light.exe"
LIT = "$(WIX_DIR)\bin\lit.exe"
SMOKE = "$(WIX_DIR)\bin\smoke.exe"
SETUPBLD = "$(WIX_DIR)\bin\setupbld.exe"

WIX_FLAGS = \
	-dqt_dir=$(QT_DIR)
	
!IFDEF DEBUG
WIX_FLAGS = $(WIX_FLAGS) \
	-ddebug=1 -dbuilddir=debug
!ELSE
WIX_FLAGS = $(WIX_FLAGS) \
	-dbuilddir=release
!ENDIF

WIX_EXTENSIONS = \
	-ext WixUIExtension -ext WixUtilExtension
	
WIX_OBJS = \
	wolfzilla.wixobj \
	WixUI_wolfzilla.wixobj

WIX_LOCALES = \
	-cultures:en-us -loc "i18n\en_us-wolfzilla.wxl"
	
.SUFFIXES: .wxs .wixobj

.wxs.wixobj:
	$(CANDLE) /nologo -o $@ -arch $(WIX_ARCH) $(WIX_FLAGS) $(WIX_EXTENSIONS) $<

all: wolfzilla.msi

wolfzilla.msi: $(WIX_OBJS)
	$(LIGHT) /nologo -o $@ $(WIX_FLAGS) $(WIX_EXTENSIONS) $(WIX_LOCALES) $**

setup.exe: wolfzilla.msi
	$(SETUPBLD) -out setup.exe -ms wolfzilla.msi -setup "$(WIX_DIR)\bin\setup.exe"

clean:
	@-erase *.wixobj wolfzilla.wixpdb wolfzilla.msi setup.exe *.log 2>NUL

distclean: clean

test: wolfzilla.msi
	$(SMOKE) wolfzilla.msi

test_install:
	-del install.log
	-msiexec /lieva install.log /i wolfzilla.msi

test_uninstall:
	-del uninstall.log
	-msiexec /lieva uninstall.log /x {5a95c1e7-7d87-46c4-8380-6a6ac5ab9a63}
	
	
